name: Deploy Website

on:
  push:
    branches: [ integration-pages ]
  pull_request:
    branches: [ integration-pages ]

jobs:
  build:
    runs-on: cloudquery-release-runner-8-cores
    defaults:
      run:
        working-directory: ./website
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - run: yarn install
      - run: yarn build
      - uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} # Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}  # Required
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}} # Required
